crits/crits

crits/emails/handlers.py

If one clicks the plus button next to the "Originating IP" field in an email, an "Address - ipv4-addr" indicator is created and related, as you would expect. However, the code looks for a String relationship when determining if the plus button should have a circle around it or not. I'm guessing this was a copy/paste error. Changing the field_type of "originating_ip" from "String" to "Address - ipv4-addr" so that the created/related Indicator is recognized.

Change field_type of "originating_ip" to "Address - ipv4-addr"

---

crits/indicators/forms.py

Campaign and campaign confidence should not be required when creating a new indicator.

Indicator upload should not require campaign

---

crits/core/data_tools.py

The strings.printable gives output that is not suitable for direct entry to a regex.
"0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~ \t\n\r\x0b\x0c" breaks:
- at the dash, which is interpreted (correctly) as the range from , to .
- at the closing bracket ], because it is not escaped.
- the rest of the line is ignored
I believe we don't really want all whitespace in a string.  It was my assumption that the 'strings' view would greatly resemble a default run of "strings" on a unix command-line.  This change gets closer to that idea.
Assuming the file includes a string like "C:\\path\to\directory\file", the current master would give:
- path
- directory
- file
And this change would result in "C:\\path\to\directory\file"

The strings tool should give paths, and should not print whitespace

---

crits/core/errors.py
crits/core/templates/500.html
crits/core/views.py
crits/dashboards/views.py
crits/urls.py

This change exposes the Exception name and the Value in the custom
500.html template. Created an "errors.py" file which contains the
custom_500 function to facilitate populating the template. This function
also formats the traceback and write it to the "crits.log" file as
DEBUG. This will allow people to disable DEBUG mode, but set logging to
DEBUG. Now the UI will be nice and clean, users will have a small bit of
information which they can relay to an admin who can find the
corresponding information in the log.

Better debugging when debug mode is not turned on.

---

UPDATING
crits/comments/comment.py
crits/core/management/commands/create_indexes.py

Fix some problems with notifications.
Indexes were not created correctly (see UPDATING) so that documents would be deleted after 30 days.
When commenting on an object don't parse usernames if they do not exist in the system.

Notification fixes

---

crits/samples/handlers.py

If the same new MD5 is entered more than once in the Bulk Upload MD5 Samples table, and the table is uploaded, multiple Sample documents are created in the DB with the same MD5. These duplicate Samples cannot be accessed through the UI and must be manually merged/removed. This problem is caused by the caching optimization; the new Sample that was just added is not in the cache, so the code creates a duplicate Sample thinking that MD5 does not yet exist.
Fixed by updating the cache when a new Sample is added.

Stop duplicate MD5s created during bulk MD5 upload

---

crits/comments/handlers.py

Comments were not appearing in the Recent Activity (Aggregate Comments) page.
Back in May 2014, notifications were moved out of the Comments collection of the DB, which eliminated the need for the 'type' field. From that point forward, adding a new Comment would not include a 'type' field, but the "get_aggregate_comments" function still queried for data using `{'type': 'comment'}`.
Modifying the query fixes this problem.

Modify query so Comments appear on Recent Activity page

---

crits/services/handlers.py

VirusTotal lookups against Domains and IP wouldn't run because somebody wanted to reset the filepointer on objects that don't have filedata attribute...
DEBUG 2015-02-06 17:09:16,312 crits.core.errors ['Traceback (most recent call last):\n', '  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n', '  File "/usr/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view\n    return view_func(request, *args, **kwargs)\n', '  File "/data/crits/crits/services/views.py", line 189, in get_form\n    return service_run(request, name, crits_type, identifier)\n', '  File "/usr/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line …

Fix filedata.seek(0) attempts against Domains and IPs

---

crits/core/handlers.py

Doing a global search, or a "Comments about Objects" advanced search, includes `{'type': 'comment'}` in the query. Since May 2014, the "type" field has not been included in new Comments, and therefore those Comments were not included in search results. This is related to PR #386.

Remove "type" field from searches for Comments

---

script/bootstrap

Version 3.0.5 is broken on OSX. This is a temporary fix backporting to 3.0.4.

Build swig from the 3.0.4 version

---

.gitignore

Especially with the new bootstrapping script it’s nice to be able to use CRITs with a VirtualEnv. The most common convention is to name this ```venv``` so it’d be great to ignore that directory since we don’t want it checked in.

Ignoring venv Directory

---

script/server

Yet another short usability script. Traditionally if you have a ```bootstrap``` script for setting up a service you’d also have a ```server``` for restarting that service. This makes it easier to come back after a restart.

Added server script

---

contrib/mongo/mongod_start.sh
script/bootstrap

Default to using `--smallfiles` with mongod. This will allow us to support "quick deployments" on smaller systems (disk) where there's not enough space for normal-sized journal files. This will usually happen on a VPS or VM where there's less than 4G of space dedicated to the VM.
Fixed some `sh` syntax issues with conditionals.
Added the keyserver changes necessary for the mongodb-org package to be installed via apt-get (the official package from 10gen).
Fixed the pgrep command so that checking the return code worked properly.
Added a conditional such that if `create_default_collections` failed, we wouldn't continue on and try to create a user.
Tested on Ubuntu 14.04 and Mavericks.

Bootstrap fixes.

---

crits/campaigns/handlers.py
crits/campaigns/urls.py
crits/campaigns/views.py
crits/core/handlers.py

Add a view which calls into get_item_names() to fetch a list of
campaigns. It takes an optional flag to get active campaigns or inactive
campaigns.
While here, add a check in get_item_names() to make sure it can not be
used to enumerate sources.

Add support for listing campaigns by name.

---

crits/core/user.py

When using LDAP auth with Active Directory, if a valid user is passed with no password, situations exist where AD will let a user bind with no password (anonymous bind) and success login is processed. Force a non-blank username and password.

Fixed bug for missing password w/ldap

---

crits/certificates/handlers.py
crits/emails/handlers.py
crits/events/handlers.py
crits/ips/handlers.py
crits/objects/object_mapper.py
crits/pcaps/handlers.py
crits/raw_data/handlers.py
crits/raw_data/raw_data.py
crits/standards/parsers.py
crits/standards/templates/import_results.html

For a long time we parsed STIX/CybOX and just created a new CRITs object or returned the current one in the database. The main issue with this is that it breaks the philosophy of running all of our data through handlers so no matter where you come from (web, API, command-line) you will be guaranteed that the same code is handling the same type of feature. This caused problems like creating Indicators but doing all of the automated fun stuff that would come along with creating an Indicator through the UI.
This change makes the Standards Parser parse out the necessary values and submit them as arguments into the appropriate handler for creating new content.
This might make the "from_stix()" or "from_cybox()" class methods deprecated, but I've left them in there for the time being until we …

Standards Parser now uses Handlers

---

crits/samples/handlers.py

When adding an Email to CRITs via a .eml or .msg file, any attachments are related to the Email TLO using a Contains/Contained_Within relationship, however using the "Add Attachment" button for an existing Email only formed the more generic "Related_To" relationship.
This change will make email attachments more consistent by using a Contains/Contained_Within relationship when adding attachments to an existing Email.

Use 'Contains' relationship when adding Email attachment

---

crits/campaigns/templates/campaign_detail.html
crits/core/handlers.py

If a Campaign name contains a special character like an apostrophe, the link on the Campaigns listing page will be broken because it has been html escaped. Further, if you access the Campaign details page, you will not be able to add an alias because the DB does not contain the template-auto-escaped form of the name.

Fix issues with special chars in Campaign names

---

crits/raw_data/handlers.py

This updates the RawData's handle_raw_data_file() to accept EmbeddedSources. Before it would only accept a strings, and the embeddedSources would get written into the database and resulting in a RawData objects that are not visible to anyone. I've essentially reused the code from Samples' handle_file() to fix this.

RawData embedded sources handling fix

---

crits/campaigns/handlers.py
crits/core/class_mapper.py
crits/core/form_consts.py
crits/core/handlers.py
crits/core/static/js/dialogs.js
crits/stats/handlers.py
crits/targets/forms.py
crits/targets/handlers.py
crits/targets/views.py
extras/www/static/js/dialogs.js

I was seeing a variety of problems when the same email address, but with different case, exists in multiple Targets.  Ideally we could consider email addresses case-insensitive and an address would only appear once in the Targets collection. While the Email TLO would retain record of how the address was actually cased, the Targets collection would consist of only lower-cased email addresses. However, this is not necessarily the case.
I made a few changes to **Targets** to address that and a couple other issues:
* Adding/Updating:
* Problem: Using “iexact” in upsert_target was sometimes causing the wrong Target to be updated. If a user updates a Target, but the same email address with different case also exists as a Target, the other Target may be updated instead.
* Fix: Now the code will …

Improve Target Visibility and Handling

---

crits/core/static/js/core.js
crits/core/static/js/dialogs.js
crits/screenshots/static/js/screenshots.js
crits/settings.py
crits/targets/templates/target.html
extras/www/static/js/core.js
extras/www/static/js/dialogs.js
extras/www/static/js/screenshots.js

This change enables Cross Site Request Forgery (CSRF) protection.
https://docs.djangoproject.com/en/1.6/ref/contrib/csrf/
Enable django middleware in settings.py:
'django.middleware.csrf.CsrfViewMiddleware'
Template forms get {% csrf token %} where required.
AJAX forms get csrf token added to the header in $.ajaxSetup()
Read the cookie
Add token to header
Non-AJAX forms are handled individually as I tested.
Read the cookie
Add token as hidden input in the form
Dynamic javascript forms
Read the cookie
Add hidden input as string before form is appended to the body

Enable Cross Site Request Forgery (CSRF) protection.

---

crits/core/templates/login.html

Need a cookie to use the ajax CSRF method, need the ajax CSRF method to work to log in, need to log in to get the cookie. Resolved this catch-22 by injecting the token into the login page. Fixes #467

Add CSRF token to login page for first-time users

---

crits/indicators/handlers.py

Need to shallow copy the jtopts_fields field otherwise the actual list will be deleted and persisted. If you keep refreshing the jtable listing for indicators then a new column will be deleted each time.
HO HO HA HA

Indicators Jtable Listing Deletes Columns on Refresh

---

requirements.txt

According to the pip documentation, "--allow-external mongoengine" should be listed on a separate line.
Please see... https://pip.pypa.io/en/stable/reference/pip_install.html#externally-hosted-files
This also fixes the whole thing for Ubuntu 14.04 install.

update to fix the pip requirement woes

---

script/bootstrap

If database file exists already, it means that the bootstrap has been run before. In such case skip the secret key generation because it might break things.
Additionally, ampersand needs to be escaped in the variable that  contains the generated secret key or sed will badly mangle the key.
Just set the SC to something like that: 
`SC='test&test'`
and run
`sed -i '' -e "s/.*SECRET_KEY.*/SECRET_KEY = \'"$SC"\'/" crits/config/database.py`
also ...
-i '' causes the sed to error our, so leaving it as -i is better. 
I also reworked the regex to a nicer form.

Bootstrap: Check for the database configuration file and fix for sed

---

crits/config/config.py

The path was one level too high
"/data/crits/crits/logs/cirts.log"
The change makes it what it should be:
"/data/crits/logs/cirts.log"

Fix the path for crits.log

---

script/bootstrap

...
from crits.core.mongo_tools import mongo_connector
File "/Users/adam/Downloads/crits/crits/core/mongo_tools.py", line 8, in <module>
import magic
File "/Library/Python/2.7/site-packages/magic.py", line 161, in <module>
raise ImportError('failed to find libmagic.  Check your installation')

Bootstrap fixes for OSX

---

UPDATING
crits/core/crits_mongoengine.py
crits/emails/email.py
crits/events/event.py
crits/objects/object_mapper.py
crits/standards/parsers.py
crits/standards/templates/import_results.html
requirements.txt

This PR is an attempt at enabling the sharing of String Indicators and TLO relationships via STIX.
Strings:
- There is no CybOX object type designed for generic strings
- This solution uses the CybOX Custom object
- Object custom_name = "crits:String"
- The single custom_property name is "value"
- This requires an update to cybox-2.1.0.11 and stix-1.1.1.5
- This is intended to address #442
Relationships:
- In order to describe via STIX the inter-object relationships, all Observables are wrapped within a STIX Indicator (I'm not a huge fan of this Observable wrapping and I expect @mgoffin won't be either, so I'm open to suggestions :smiley:)
- The STIX Indicator title and description indicate that the Indicator is simply a wrapper
- The STIX Indicator's related_indicators attribute …

Sharing String Indicators and Relationships via STIX

---

crits/core/api.py

Fixes a key miss that was happening on PATCH API calls for actors. The key was 'Actor' when it should've been 'Actors'
Relevant discussion: https://github.com/crits/crits/pull/449

Changes actions API key from 'Actor' => 'Actors'

---

script/bootstrap

Summary of changes:
- addirng Universe repo for Ubuntu. Without universe repo some of the dependencies are missing on Ubuntu.
- Generate the random key without using the python script. When apt-get would fail, the user would end up with an empty SECRET_KEY, and more failures that are harder to troubleshoot. 
- Change unrar to unrar-free to fix ubuntu-15.04
- remove an extra space
We can now probably retire crits/contrib/gen_secret_key.py

Bootstrap updates

---

crits/relationships/handlers.py

The condition where an invalid right_type and right_id were passed to forge relationship was not handled. I added that conditional branch and also made the error message more specific for both a left and right side failure.

Fix issue with forge_relationship

---

script/bootstrap

Apparently we need to escape slash character for sed or it will error out when // shows up in the input because of the special meaning of double slash in sed on OSX.

Update bootstrap's SECRET_KEY handling for OSX

---

script/bootstrap

Now we fix a "double backslash" case.
I've kicked off a test with couple of 100k iterations and there were no more errors.

Update bootstrap's SECRET_KEY handling for OSX #2

---

crits/domains/handlers.py

Add a workaround to the tld parser. If it can't find a domain then re-query the tld collection to get the most up to date information. Fixes #513.
Keep in mind this would not be a solution in the situation where someone decides to remove TLDs. In that case you'd need to restart the web server.

Domain TLDs Stale

---

crits/dashboards/utilities.py

If campaign name was not in English,
"UnicodeEncodeError as /dashbaords/" is received with exception "'ascii' codec can't encode characters in position ... ".
the problem is in line 62: href += str(object[key]) + "/" 
in non-English name situation line will fail.

Fixed unsupported Unicode Campaign names on Dashboards ->Top Campaigns table 

---

crits/core/handlers.py

When searching any lexer errors would throw an unhandled exception.
Catch them all and return any error messages back for the view to pass
along.
This is easiest to trigger by searching for a "

Catch any lexer errors.

---

crits/samples/handlers.py

"Contained_Within" was missed, this should be the proper fix to get the attachments from emails properly related. There is a PR to fix these things for services https://github.com/crits/crits_services/pull/141

Fix a missed relationship conversion

---

crits/core/crits_mongoengine.py
crits/core/data_tools.py
crits/core/fields.py
crits/emails/handlers.py
crits/indicators/handlers.py

I'd like to change the instances of StringIO to BytesIO for more future proof  implementation.

StringIO to BytesIO changes for portability

---

crits/core/management/commands/prep.py

Removing obsolete references to sectors in prep.py since this functionality is now in CRITs vocabularies. This was preventing users from running python manage.py upgrade -S [and -D]
Closes #570

Remove Sector References from prep.py

---

crits/emails/handlers.py

When uploading a RAW email, the error message "No items found" is cryptic because normally you would only get that error if the EML is malformed.
Repeatable by giving invalid EML. 
Doesn't work:
```
from:me
to:you
```
Works:
```
from: me
to: you
```

Better Parse EML Error Message

---

crits/emails/handlers.py

This fixes a problem with some weird .msg attachments, at least you can see what fails. https://github.com/crits/crits/issues/556
The sample that was triggering the issue goes in ok, but it tells me that one of the attachments has no data.

Fix for msg upload issue

---

crits/core/handlers.py

Best example of this is in bucket lists. Put this as a bucket list on an
item:
/textarea><sCrIpt>alert('xss3')</ScrIPt>
then view the "/bucket/list/" url and you should get an alert.
Fix it by escaping the term.

Fix XSS in jtable name.

---

UPDATING
crits/config/config.py
crits/core/management/commands/test_install.py
crits/settings.py
script/bootstrap

There is a large difference of supported file formats, it's better to use 7z rather than the very limited 7za
To compare, please see the following two outputs:
$ 7za i
```
7-Zip (A) [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=utf8,Utf16=on,HugeFiles=on,8 CPUs)
Formats:
CK  bzip2   bz2 bzip2 tbz2 (.tar) tbz (.tar)   B Z h 
CK  gzip    gz gzip tgz (.tar) tpz (.tar)   1F 8B 08 
K  lzma    lzma            
K  lzma86  lzma86          
Ppmd    pmd             8F AF AC 84 
Split   001             
CK  xz      xz txz (.tar)   FD 7 z X Z 00 
Z       z taz (.tar)    1F 9D 
C   7z      7z              7 z BC AF ' 1C 
Cab     cab             M S C F 
C   tar     tar             u s t a r 
C   zip     zip jar xpi odt ods docx xlsx   P K 03 04 
Codecs:
```
$ 7z …

use 7z rather than 7za

---

crits/core/templatetags/filters.py

This fixes the type filter calling itself rather than the built-in type function.
The type is also converted to a string before being returned to match the documented return type.

Fix infinite recursion bug in type filter and return a string as documented

---

Vagrantfile
crits/services/urls.py
crits/settings.py
fabfile.py
script/bootstrap

Make it easier to have some services installed by default in a Vagrant-provisioned dev environment. The next step would be to automatically install dependencies for services that need them, so those services work too.
cc @packet-rat

First cut at Service provisioning in Vagrant

---

crits/emails/api.py
crits/emails/forms.py
crits/emails/handlers.py
crits/emails/views.py

Previously one just couldn't specify ticket number nor bucket_list for an email being uploaded.
This change includes changes to upload forms, and also for the API uploads.

Added tickets and bucket_list support for uploaded emails.

---

crits/emails/api.py

Added a call to str() on the returned objectId to allow success
- Possibly, a more correct fix would be to ensure obj_id is a string when created in handler.py, or to use a mongoEngine that allows an ObjectId to be serialized.

Returning the ObjectId was failing in JSON serialize for API submission

---

crits/samples/handlers.py

This should give a meaningful error message when zip7_path is misconfigured

Add a check for 7z in unzip_file()

---

crits/services/urls.py
crits/settings.py
script/bootstrap

Though not ideal, circular import problems were preventing the templates from ever loading, even if dependencies were installed. IMO, this was worse than the state after this PR, where CRITs will fail to load unless you manually remove services with missing dependencies.

Remove import checks for service templates

---

crits/core/management/commands/generate_notifications.py

Filter out entries containing None obj_type and None obj_id from being added to notifications since useless links are created...
The entries that are filtered out are of the form:
\<someuser\> updated a(n) None you are subscribed to: https://\<crits URL\>/details/None/None

Filter out useless notifications

---

crits/core/crits_mongoengine.py
crits/emails/static/js/emails.js
crits/emails/templates/email_detail.html
crits/emails/views.py
crits/indicators/handlers.py
extras/www/static/js/emails.js

When on a email details page, clicking the plus sign (+) normally creates an indicator. This was broken because in emails/views.py the indicator types were being set to the following types which are not in the vocabulary anymore. So when you try to create an indicator it complains that it is not a valid indicator type.
```
if header_field in ("from_address, sender, reply_to"):
ind_type = "Address - e-mail"
elif header_field in ("originating_ip", "x_originating_ip"):
ind_type = "Address - ipv4-addr"
else:
ind_type = "String"
```
I updated the code to use the new vocabulary types by putting the types in the correct locations in the email_details.html template and updating the back end to also grab the new field.
I strongly suggest reviewing the code to make sure nothing is wrong because I …

Email Create Indicator Fix Plus Sign (+)

---

crits/services/core.py

In _add_result, instead of doing a loop to update the dict,just use the builtin .update() to do the same thing
Also added _add_results function to speed up adding large amounts of data.  I have some test samples that add a lot of data, and it was taking > 3 hours for it finish.  Using _add_results, it took 7 seconds.

Speed up adding results

---

crits/services/api.py
crits/services/handlers.py
documentation/help_main.html
documentation/help_main.txt

**Issue**
The service api already exposes the possibility to add results to a TLO which is very important for distributed services. However, a distinct HTTP request is necessary for each result set which puts a lot of unnecessary extra strain on both CRITs and the distributed service.
**Proposal**
By adding the option to send result sets in batch as JSON lists it would be possible to handle many result sets on both sides with a single HTTP request, eliminating a lot of overhead.
**Improvements**
During our internal testing we pushed 5000 result sets to 100 TLOs each on a CRITs machine on the same network. Depending on the size of the result sets we have seen a 20% to 50% speed improvement. We assume the improvement would be even greater for machines not on the same network.
**Known …

Added possibility to add results in batch via the api

---

crits/settings.py

git was running not inside the git repo, added cwd param to put it in the right spot.
It should fix #645 issue when running on a webserver like Apache.

Run git in SITE_ROOT

---

crits/core/management/commands/create_indexes.py
crits/indicators/handlers.py
crits/indicators/indicator.py
crits/indicators/migrate.py

We now store the value as-is, but store the lowered value in a "lower"
attribute of the Indicator. When searching for duplicates we will search
against the "lower" field using the value.lower() of the new Indicator.
If a match is found, we will update the existing Indicator as we
normally would on a match, but we will append to the "description" field
what the actual value was that was added. This allows people to store
historical reference for camelcase values that are different but the
same when lowered.
This comes with a schema bump for Indicators so we can backfill the
"lower" field.

Allows for camelcase Indicator values.

---

crits/core/handlers.py
crits/core/views.py

When adding actions to a TLO, validate that the action type can be added and also the entire form itself.
`form.is_valid()` was being called but no action was taken on it.... so a user could add any action type they wanted? Is that the desired behavior?
Refactored `get_actions_for_tlo()` and created `get_action_types_for_tlo()` in handlers so the code can be reused.

When adding actions to a TLO, validate that the action type can be added

---

crits/samples/handlers.py

Solution: This pull request will identify the newest available template for a service.
Issue: CRITs queries the analytic_results database to identify the a template path of a service. This in theory could allow CRITs to use a template that is unique for that version of the service. However, the way CRITs is used does not allow this to occur. This is because the services overwrite their core code on every new version. Additionally, the previous method would make it cumbersome to add or change custom templates.

Identify the newest available template for each service on get_sample_details

---

crits/signatures/static/js/signatures.js
extras/www/static/js/signatures.js

The Signature TLO details page was posting/recording updates
to the data type dependency list during page load. This was due to
the location of the update code when performing TagIt activities.
After reviewing the methodology for how Buckets handled this, a
similar update was made to the Signature TLO. Now, the add, update, and
delete calls are only performed after the page has been loaded.
This issue being corrected didn't seem to result in any bad TLO data, just
unnecessary additional calls to the server and an incorrect auditlog entry
added during normal signature details page access.

Update Signature TLO Details Page to Not Record Updates During Onload

---

crits/core/api.py
crits/indicators/handlers.py

A typo in core/api was preventing RawData PATCH API requests from completing.  
Attempting to create an Indicator object using a POST API request also fails unless a description is provided.  This is due to an attempt to strip a NoneType object, which is the default value for the "description" argument (description = None).

Resolved issues with Indicator POST and RawData PATCH requests.

---

script/bootstrap

Pillow fails without c-headers for libjpeg. I think this is the right way to fix this issue, since we're installing Pillow from the PIP, and the native package manager can't resolve the dependencies.

Add libjpeg-development package for Pillow

---

script/bootstrap

Chmod in this case is not desired, since it modifies permissions on the files after bootstrap is run, which impacts the git repo. E.g. git diff shows lots of permission changes.

Remove chmod from bootstrap

---

crits/core/handlers.py

resolve needs only the '/whatever/' part, and it doesn't resolve if there are params in the string.

A small little fix to the redirect fix

---

crits/core/handlers.py

I'm not sure if we use POST anywhere, but definitely most things work with GET.  Django 1.9 deprecates request.REQUEST.

Quick fix for Django 1.9

---

crits/objects/handlers.py

In reference to #701 
When using the PATCH API, the 'obj' argument is passed to all handler functions. The add_object function has a parameter 'obj'. The add_object parameter needs to be renamed to prevent any conflict.

Modified add_object handler to prevent conflict with PATCH API requests.

---

DEPENDENCIES

This simply updates conflicting version numbers to reduce confusion. I did not try to add anything new to DEPENDENCIES from requirements.txt.

Update versions in DEPENDENCIES to match those in requirements.txt

---

crits/core/handlers.py
crits/services/views.py

This has been annoying me for the LONGEST time. These are control panel changes.
Changed users page to sort by last login date by default.
Changed services page to sort by name, case insensitively.

Sort services case insensitively, sort users by login date by default.

---

crits/core/handlers.py

When attempting to add preferred actions when multiple preferred actions exist, the same "date" value, which serves as a key, was being added to all actions.  This prevented the user from removing and/or modifying the actions.

Moved the datetime variable to prevent actions with duplicate dates.

---

crits/emails/handlers.py

If an Email field does not exist in the DB, then its value is returned to the template as None. The template then displays the value as text "None" which may be misleading as it cannot be differentiated from an actual value of string "None". This also leads to an error when an indicator type/value pair is attempted to be generated from the email field as None suggests the desired field doesn't exist. To make matters worse, if a user clicks to edit one of these Email fields, but doesn't actually change it, the field value will be saved as string "None" in the DB.

Return Email field value as empty string when not in DB

---

crits/indicators/handlers.py

When loading a TLO details page that has Objects, the code attempts to determine if there are any matching Indicators by analyzing the TLO's relationships list. The code responsible for this was not adjusted to work with the new vocabulary and thus looks for the old "name" field that no longer exists.

Modify type/value pair extraction for new vocab

---

crits/core/crits_mongoengine.py
crits/core/static/js/bulk_add_default.js
crits/objects/handlers.py
crits/relationships/handlers.py
extras/www/static/js/bulk_add_default.js

Bulk uploading large quantities of Objects was taking an extremely long time, especially when the "Add Indicator" option was selected. I found that a huge portion of the time was spent saving the entire TLO back to the DB after adding the Object, and then again after adding the relationship to the Indicator.  As more and more Objects/Relationships are added, the document takes even longer to write to the DB. By using `TLO.update(add_to_set__xxxx=xxxx)` to insert the new object/relationship, rather than `TLO.save()`, uploading a sample set of 100 objects (and adding Indicators for each) took ~10% as long to complete. 
I think there may be additional performance improvements by caching the database writes until each block of 50 objects have been processed, but the solution in this PR is a …

Improve Performance of Object & Relationship Creation

---

crits/core/data_tools.py
crits/core/handlers.py
crits/indicators/templates/indicator_detail.html
crits/samples/sample.py

TLO download had a number of issues. Certain combinations of options were leading to a `string indices must be integers, not str` error, and certain form options that didn't result in error weren't producing expected results. 
Having an empty string in the DB for a Zip Password was also lead to an exception. This will now default to "infected" as stated in the function comments.

Fix TLO Download functionality

---

crits/services/handlers.py

Occasionally `local_obj.obj.filedata` will evaluate to True, but it won't actually have the `.seek()` attribute. This prevents an exception in that case.

Check for "seek" attribute before seeking

---

crits/samples/handlers.py

Binary data shouldn't be required for triage to be run on a Sample. Valuable analysis can be performed using only the Sample's metadata.  This change was originally submitted as PR #1375 of legacy, but was lost during the open source transition.

Allow triage of Samples with no binary

---

crits/emails/handlers.py

Fix an issue where the "To" field on the email detalis page would never be updated if you click the "pencil" thing because of a naming mismatch.

Email "To" Field Never Updates On Details Page

---

crits/samples/sample.py

Otherwise, line 171 may try to treat None as a list and crash. This has been breaking sample API searches for me.
Can someone else give this a whirl for me, just to verify that it doesn't break a thing?

default exclude param to empty list

---

crits/core/crits_mongoengine.py
crits/core/data_tools.py

The None type will cause a TypeError if there isn't some sort of other checking
prior to trying to use the parameter as a list
Continuation of findings from #763

Fix array params where defaulting to None

---

crits/raw_data/handlers.py

Otherwise it just blows up. I suppose this is just a "helper", and the right fix should be to put this at whatever is calling handle_raw_data_file(), because whatever is passed should be a string and not unicode.

If the raw data is unicode, then it should be encoded as utf-8

---

crits/raw_data/handlers.py

I forgot to remove redundant encode()

Remove redundant encode

---

crits/core/crits_mongoengine.py

Occasionally the passed-in TLO instance is still used after the call to add_relationship, and appending the new relationship here saves having to hit the database for a reload.

Append new relationship to passed-in TLO instance

---

crits/ips/handlers.py

The `ip_add_update()` handler function for IP TLOs did not support populating the IP's description field. This adds description as a parameter of that function, and also adds support in `add_new_ip()`

Add description field for ip_add_update()

---

crits/core/static/js/dialogs.js
extras/www/static/js/dialogs.js

Each time a user opens the "New Action" form, the set of available Action Types are loaded into the Action Type dropdown.  If a user opens and closes the "New Action" form repeatedly, the list grows each time with duplicates.  This fix clears the contents of the Action Type dropdown before it is populated.

Prevent loading of duplicate Action form values

---

crits/emails/handlers.py
crits/emails/views.py
crits/events/templates/event_detail.html
crits/events/urls.py
crits/events/views.py
crits/indicators/handlers.py

The EML handle functions still had parent id/type parameters, and the Add Sample button on Events used an upload_sample function, that had both been effectively replaced by the general Add Related TLO functionality, so it made sense to remove them.  In the process I fixed an issue with the Indicator Blob/CSV upload, and made the email functions more consistent with each other.  While I was at it, I tried to make things respect the PEP8 79 character limit.

Refactor, cleanup, and fix Email functions

---

crits/indicators/indicator.py
crits/indicators/static/js/indicators.js
extras/www/static/js/indicators.js

Rather than simply restricting removal of the last item in the list, when the user attempts to remove the last item, this will replace that last item with the `Unknown` option.
Also, if a user manually adds an item to the list in the Indicator Details view, this will automatically remove `Unknown` if it exists.  Previously this functionality only worked when adding from the Add Indicator form.
Further, this removes `Unknown` as an option in the suggestions list, but still allows it to exist as the only item in a list.
Used the `append` parameter to determine whether `Unknown` should be removed from an update to the list.
@mgoffin: Curious what you think about these changes. I think they are a little better for the user, but still fit with your vision.

Potential Improvements to Attack/Threat Type Lists

---

crits/indicators/indicator.py

I somehow did not include a change for Attack Type that I had made for Threat Type. This should fix that.  Without this change, if you remove the last item in the Attack Type list, it will appear that the last item was replaced with `Unknown`, but if you check the DB, it won't actually have been replaced.

Fix Missing Line Change for Attack Type List

---

crits/core/data_tools.py
crits/objects/handlers.py
crits/pcaps/views.py
crits/samples/handlers.py
crits/samples/templates/samples_uploadList.html
crits/samples/views.py

This is really rough code as the sample uploading code is a freaking
mess. This will allow for a single PCAP to be uploaded or a set of PCAPs
in a zip, or theoretically a zip containing both samples and PCAPs. It
will detect the PCAP by magic number and upload it as a PCAP instead. In
bulk situations it will return just the MD5 of the PCAP. This makes it
hard to determine in the upload list whether it was a sample or a PCAP,
so for now there are links to both details pages, so if it's a sample or
PCAP one of the links will work.
This also exposed some issues where the good informational messages in
Sample uploading was being masked by a default message. This was fixed
but caused other errors. I hope those were fixed in this.

If someone uploads a PCAP as a sample, detect it and DTRT.

---

crits/core/api.py
crits/urls.py
crits/vocabulary/api.py

This is an API resource that I created awhile ago to provide programmatic access to each CRITs vocabulary set.  We had a need to be able to pull the list of Indicator Types, in particular, so while I was at it, I made all of the vocabulary sets available.  It's not perfect, but gets the job done.  Figure I'd throw it out there so people could take a look at it.
The following URL path will return every vocabulary set:
`/api/v1/vocab/`
Providing a vocabulary class name, like below, will only return that particular set:
`/api/v1/vocab/IndicatorTypes/`

Vocabulary API Resource

---

requirements.txt
script/bootstrap

- Allow the bootstrap to run on Linux Mint
- use the fix for M2Crypto compile on more platforms
- Remove deprecated option: --allow-external

bootstrap fixes

---

crits/core/management/commands/create_indexes.py
crits/samples/sample.py

1) impfuzzy should have an index just like ssdeep
2) Samples listing didn't allow to sort by "Store ID", the index is in place for this, and all the other TLOs are doing it

two small index fixes

---

extras/httpd.conf
extras/rhel_ssl.conf
extras/sites-available/default-ssl

I was getting errors stating that various files in `/data/crits/extras/www/img/` could not be found. I think the problem stemmed from a typo in these example files, so I thought I should fix them up.  Of course, let me know if I'm missing something here.

Fix '/img/' Web Server Alias

---

crits/core/crits_mongoengine.py
crits/core/handlers.py
crits/core/static/js/dialogs.js
crits/core/templates/action_row_widget.html
crits/core/views.py
extras/www/static/js/data.js
extras/www/static/js/dialogs.js
extras/www/static/js/key_nav.js

There were situations with preferred actions where each action added
would get the exact same datetime of when it was added. This caused
issues with editing and deleting since we keyed off of the datetime
only. This change modifies a couple things.
First, we now get a new datetime for each preferred action added.
Second, since that doesn't 100% guarantee uniqueness, we now require the
action type to be passed in as well when deleting. Third, we no longer
allow for editing the action type and it is now used as well as the
datetime to find the action you are editing.
Ran a collectstatic which picked up a couple other changes that were
lingering and never collected before.

This fixes an issue with editing/deleting actions.

---

crits/settings.py

I just noticed that we don't need that auth backend, and it broke the auth for scripts ran through "manage.py runscript"

Fix auth for running scripts

---

crits/stats/handlers.py

Every time the mapreduce job runs, regardless of whether or not the email_count has changed, CRITs re-writes to the DB each Target where the count is not zero. While somewhat trivial, unnecessary DB write operations should probably be avoided.  Additionally, the write operation updates the "modified" timestamp, which could be misleading.
Same thing for division email_count.

Only Write Target email_count to DB if Value Changes

---

crits/raw_data/templates/raw_data_details.html

cgi_escape was double escaping the content, there was a difference between raw_data content in Details tab vs RawData tab.

Remove unnecessary cgi_escape()

---

crits/core/management/commands/mapreduces.py

Is there a reason that this function is called twice in a row?

Remove duplicate call to generate_filetypes()

---

crits/emails/handlers.py

In Python 2.7, StringIO expects a unicode, not a str.  However, the default object returned from the .get() call is a null string.

set default object to unicode to match expected type on StringIO

---

crits/core/handlers.py

In action_remove, the parameter 'action' is overwritten by the patch operation parameter 'action'. 
The end result dict that would be required to be sent to the server would be something like 
>{'action': 'action_remove', 'action': '<actionname>', 'date': '<actiondate>'}. 
Two params with the same name is no bueno.

action_remove API param rename

---

crits/services/handlers.py

When uploading a new Target TLO, I encounter the following exception in the `finish_task` function:
```
HTTP/1.1" 200 799
Process Process-4:
Traceback (most recent call last):
File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "/opt/crits/crits/services/core.py", line 472, in execute
self.current_task.username)
File "/opt/crits/crits/services/handlers.py", line 470, in finish_task
obj = klass.objects(id=object_id, source__name__in=sources).first()
File "/usr/lib/python2.7/site-packages/mongoengine/queryset/base.py", line 264, in first
result = queryset[0]
File "/usr/lib/python2.7/site-packages/mongoengine/queryset/base.py", line …
```

exception on Target upload from no 'source' field

---

crits/indicators/templates/indicator_detail.html

I just happened upon this.  I believe these should all be "indicator.ind_type" instead of "indicator.type".

Fix linking of certain Indicator values on indicator_detail page

---

crits/samples/sample.py

Adding a feature to check if a sample is a Office file or not based on the file header hex bytes. Hopefully this is the correct way to check against the sample in CRITs.

Adding feature to check to see if the sample is a Office file.

---

crits/dashboards/templates/dashboard.html

A typo, or copy-paste error, was preventing proper sorting of custom dashboard tables.  This change enables the sort direction value to be retrieved by the database.

Fix sort direction of dashboard tables

---

crits/samples/handlers.py

Having the default argument for the `source` parameter of Sample's `handle_file` function set to "Generic" has led to some problems.  If the `source` argument is an EmbeddedSource instance, then the method and reference are part of that instance and likely will not be included as separate arguments. However, the code functions in such a way that a provided method or reference argument will override the values in the EmbeddedSource instance, which leads to the method being overwritten by the default value "Generic".
I'm not sure why the default was "Generic" anyway.

Remove "Generic" default Sample upload Source Method

---

crits/core/handlers.py
crits/core/views.py

The `audit_listing` view is not setup to handle a Audit Log CSV request and there is no handler to generate the Audit Log CSV. This PR adds those.

Add CSV Download for Audit Log

---

crits/core/user.py
crits/indicators/handlers.py

Check for valid objects before using it.

Validate check_source_tlp() input before trying to use it.

---

crits/ips/handlers.py

Can't create IP because of user/analyst usages. Fixing mixups between user and analyst.

Can't create IP because of user/analyst 

---

crits/services/analysis_result.py

This thing broke after https://github.com/MongoEngine/mongoengine/pull/1497 was merged.
I'm not really sure if this is the right fix, it seems that mongoengine/fields.py#L625 added a check for 'dict'.

This change makes CRITs work on Mongoengine 0.12

---

crits/core/crits_mongoengine.py

This addresses the following:
- If the Indicator list was exported to CSV, the "actions" column would display something like `[<EmbeddedAction: EmbeddedAction object>, <EmbeddedAction: EmbeddedAction object>, <EmbeddedAction: EmbeddedAction object>]` instead of the action_types.  Similarly, the bucket_list column was not exporting cleanly.
- The code allowed for a rare case where a column header could be included for which no data was provided. This would lead to mismatched rows and encode/decode issues.

Fix CSV export of actions & simple list fields

---

crits/emails/handlers.py

When x_originating_ip is set to an IPv6 value, the previous findall function returns 0 matches, causing an error. This fixes that and either sets x_originating_ip to the IPv6 value or the first IPv4 matched by the regex.

Fix regex find assumption

---

crits/core/api.py

One of our team realized that c-_id queries in the API were broken (a small if/elif swap bug). When digging deeper, we decided it would be nice to implement the __in and __nin API operator extensions here, as the tastypie /set/ endpoint is painfully inefficient for fetching a specific list of indicators by id.
So - fixed the ?c-_id bug, and then added support for c-_id__in and c-_id__nin to the API.

Fix and improve API queries for c-_id on TLOs

---

crits/core/crits_mongoengine.py

Rather than performing a mongoengine lookup on each TLO id in a
relationship list (the 'value' field in the BSON), group the TLO Ids
together in a bulk lookup using id__in, and run exactly one search
against each collection to fetch the population of related indicators
in that collection. This hopefully will speed up page rendering where
a TLO has many (> 1000's) of relationships.

Optimization: Run bulk queries, per rel. type

---

crits/indicators/handlers.py

Certain bad Indicator values can lead to errors during validation.  Particularly an email address like "abc@", or a URI like "http:///apple/butter/juice.aspx".

Return error if no domain/IP component in URI or Email Address

---

crits/core/crits_mongoengine.py
crits/core/handlers.py
crits/core/user.py
crits/core/views.py

There was an issue where the last logged in user would overwrite the ACL
for all users who already logged in and were active.
To fix this I decided to write the user's ACL to the database. This will
cause slightly more overhead in pulling the user document out of the
database, but the `acl` attribute will act as the previously-known
"cached" version of the ACL.
To accommodate the need for updating, there's also a new
`acl_needs_update` attribute for the user. This will generally be set to
False, but two conditions will set this to True:
1) The user's account has been changed in ANY way.
2) A role the user has been granted has been changed in ANY way.
If those conditions are met, the user's account will get flagged.
Whenever we do a `.has_access_to()` check on that user, if they are …

Fix an issue with lingering ACL overwrites.

---

crits/core/user.py

There were some issues lingering with ACL checks that still assumed ACL was an object and not a dictionary. This was causing some edge-case issues with login attempts.

Remove acl attr

---

crits/comments/comment.py
crits/core/static/js/dialogs.js
extras/www/static/js/dialogs.js

If a user types a Comment containing newlines, those newlines are ignored when the Comment is displayed.  This converts the newline character `/n` to an html line break `<br>`, so that the intended newlines are displayed.

Allow newlines in Comments

---

crits/samples/sample.py

In rare cases, the "magic" library can return a very long string for a Sample's `filetype` field. This results in an error because the value is too long for MongoDB to index.  Truncating the result at 1000 characters to make it fit.

Limit length of Sample metadata "filetype" field

---

crits/samples/views.py

When a zip file containing a single file inside is uploaded the code was blowing up since a dict was expected in that code path for regular file upload. This small change fixes that case.

Fix zip file upload

---

Dockerfile

Error output from running the following *docker* command:```sudo docker build -t crits .```
```bash
Step 12/14 : RUN sh contrib/mongo/mongod_start.sh && python manage.py users -u admin -p "pass1PASS123!" -s -i -a -A -e admin@crits.crits -f "first" -l "last" -o "no-org"
---> Running in 2e3d47282b78
about to fork child process, waiting until server is ready for connections.
forked process: 8
child process started successfully, parent exiting
Usage: manage.py users [options]
Add and edit a CRITs user. If "-a" is not used, we will try to edit.            
manage.py: error: no such option: -A
```                                                                            
The *-A* option is no longer available in **crits/core/management/commands/users.py**
The *administrator* option was removed …

Remove user management -A option from Dockerfile

---

crits/emails/handlers.py

It look like the service_list was not added by some accident, like it is present in the other TLOs. This was causing intermittent manifestation of "No services available" in Services tabs for Emails.

Fix the service_list for emails

---

crits/core/crits_mongoengine.py

This change actually fixes the quirk that happens on newer versions of mongoengine.
There is an issue in CRITs' modified version of only(), it should just pass empty set of fileds without adding in schema_version in there when an empty set of fields is passed. This actually makes queries for audit_log and dashboard work as they should on mongoengine versions later than 0.8.x.

Fix a corner case in only()

---

crits/core/user.py

get_access_list() bombs out when an user has no roles assigned, this PR provides a fix and makes a note of it in the log.

Fix get_access_list() if user has no roles

---

crits/core/mongo_tools.py
crits/settings.py

http://api.mongodb.com/python/current/faq.html#how-does-connection-pooling-work-in-pymongo
One connection is established in settings.py, and now is used in
mongo_connector() and gridfs_connector(). Previously, every call
was opening a brand new connection to the database.

Use pooled connection for pymongo based queries.

---

crits/samples/handlers.py

source_tlp was not passed to unzip_file() in handle_unzip_file() resulting in an error, overwritten by success...
```   # if no proper source has been provided, don't add the sample
if len(sample.source) == 0:
retVal['message'] += "The sample does not have a source."
retVal['success'] = False
```
Perhaps it would also make sense to add "return retVal" at this point.

Fix Un7zip

---

crits/core/api.py
crits/core/handlers.py
crits/core/user.py

First run at attempt to fix Issue #913 and push the TLP filters to the database query, instead of
doing it on the server-side. This is especially expensive because it causes
paginated views to fetch all elements from a collection. We have over 2M objects
in some collections, and this made the application unusable, regardless of
hardware, post tlp-addition.
I have left the "old code" in place, but commented out, so that the crew
can compare the intent/logic of the original implementation with my refactor.
Once I get thumbs-up, or tweaks that correct errors I've introduced, I'll
commit the removal of the commented-out code.
It is super-fast now, btw.

Attempt to fix performance problem raised in Issue #913

---

crits/config/config.py
crits/config/forms.py
crits/config/templates/config.html
crits/core/handlers.py

This will allow an admin to choose the default/maximum number of rows for downloads to CSV. This is the limit used when a user clicks the "CSV" button at the top-right of a jTable.  Historically this was arbitrarily limited to 10000 rows, but now can be adjusted in the control panel.
@mgoffin: Let me know if this aligns with what you were expecting following our conversation.

Make maximum CSV rows configurable

---

crits/notifications/processor.py

Modifying a TLO leads to the generation of an audit notification listing which fields were changed, and in the case of a list field, which values were added/removed.  These values are forced to Unicode, but no encoding is given. If the added/removed values contain non-ASCII characters, the Unicode Decode fails. This fix tells it to use UTF-8.

Handle non-ASCII in changed field notifications

---

crits/indicators/templates/indicator_detail.html

See line 164 - the old text was:
{% if INDICATORACL|has_access_to:user.STATUS_READ|has_access_to:user %}
and *should* read:
{% if IndicatorACL.STATUS_READ|has_access_to:user %}

Fix problem with "status" display ACL

---

crits/core/api.py

Both of these TLOs would not return any data via the API.  This patch resolves that issue

Fix problem with campaigns & targets

---

crits/core/api.py

The <code>querydict[field] = {op: val}</code> operation seems to be failing if the
user requests <code>?c-value__ne=something</code>, and the fix appears to be
<code>remove_quotes(val)</code>. So fixing this.
Additionally, when making an API call with <code>regex=1</code>, there didn't appear
to be a mechanism to force *some* fields to be non-regex searches. Since
this is a potential query optimization (limiting what regex gets applied
to), I added support for <code>c-field__eq</code>, which will use the existing "regex
override" logic to force any specific field(s) to be equality-matched, rather
than regex matched.
Using the documentation
https://docs.mongodb.com/manual/reference/operator/query/eq/#op._S_eq
I simplify <code>{'field': {'$eq': remove_quotes(val)}}</code> to be …

Add 'c-field__eq' support to API, and fix de-quote

---

crits/objects/templates/bulk_add_object_inline.html

The "bulk_add_default.js" file has a call to function `processObjectTypeCellChange` which is implemented in file "handsontable.js", but "bulk_add_default.js" is loaded before "handsontable.js", occasionally leading to a `processObjectTypeCellChange is not a function` error.
Including "handsontable.js" earlier addresses this error and doesn't appear to hurt anything.

Occasional Undefined Function "processObjectTypeCellChange" Error

---

crits/core/views.py

When XMLHttpRequest attempts to authenticate an already-logged-in
session, the response is rendered as HTML. This causes the "user is
already authenticated" session cookie check to only occur on the /login/
route view when the request is not Ajax. If it is Ajax, the code
proceeds to create a new session and return JSON code. The HTML response
in the current behavior causes anything expecting JSON to generate a
parsing error.

Fix case where XHR login reauths an existing session

---

crits/core/api.py

This feature extends the API with a "sort=" parameter that can take a
list of mongo field names to sort using the mongoengine order_by(...)
call. This supports ascending sort (sort=field), descending sort
(sort=-field) and even multi-field sorting
(sort=field1,field2,-field3,...).

Add "sort=" param to API and support API sorting

---

crits/emails/api.py

When uploading an email in the EML format to the CRITS database via the API the 'handle_eml' function passed the parameter in the incorrect order leading to the return of the error message "handle_eml() got multiple values for keyword argument 'tlp'". This fix that by passing the parameters explicitly during the function call so the correct data goes to the correct parameters in the handle_eml function. This fixes the error in #952

Parameter fix for "handle_eml" call in emails/api

---

crits/core/api.py

Basically, there are some cases where the value of a field in the query
string is represented as a comma-separated list of values. There is code
present earlier in this function to identify these and do the
tokenize-and-listify operation. However, that renders val as a list,
rather than string, type by the time it gets to the code to populate the
field constraint in the query dict (which is coded to call
remove_quotes(val) ).
So the solution is to test whether val is a list, and if it isn't, run
the remove_quotes(val). Otherwise, just pass the already-decoded list as
the rvalue in the assignment.

Attempt to chase a bug I introduced with the __ne support

---

crits/core/api.py

In the cases where val was a str type, this would always run the
remove_quotes function. However, if the val was anything other than a
list type (such as a datetime), it would also attempt this translation.
This change limits the translation to only occur on str types, which I
think is the appropriate action.

Call remove_quotes only if val is a str

---

crits/core/management/commands/setconfig.py

setconfig command is broken after move to Django 1.8+, which required replacing optparse with Django provided argparse based solution. It looks like I missed one important piece...
How it should be:
$ python manage.py setconfig debug False
A CRITs configuration already exists. Skipping default creation.
Setting [debug] to a value of [False]
Saving CRITs configuration.
How it is now:
$ python manage.py setconfig debug False
usage: manage.py setconfig [-h] [--version] [-v {0,1,2,3}]
[--settings SETTINGS] [--pythonpath PYTHONPATH]
[--traceback] [--no-color] [--reset_config]
[--create_config] [--reinsert_config]
manage.py setconfig: error: unrecognized arguments: debug False
After the fix:
$ python manage.py setconfig debug False
A CRITs configuration already exists. Skipping default …

Fix setconfig called via manage.py

---

crits/objects/handlers.py
crits/objects/views.py

Fix for Tools -> Objects -> AddObject
Fix Add indicator (+) on table of objects  on Sample Details page

fixes for add indicators in two spots

---

crits/services/analysis_result.py

On mongoengine 0.16.x we get the following error:
...
from crits.services.analysis_result import EmbeddedAnalysisResultLog, AnalysisConfig
File "/data/crits/crits/services/analysis_result.py", line 31, in <module>
Document):
File "/data/crits/crits/services/analysis_result.py", line 91, in AnalysisResult
results = ListField(DynamicField(DictField))
File "/data/crits/venv2/local/lib/python2.7/site-packages/mongoengine/base/fields.py", line 89, in __init__
raise TypeError('db_field should be a string.')
TypeError: db_field should be a string.
This change has already been implemented on 4-master.

Fix the issue with the latest mongoengine

---

crits/config/forms.py

To adhere to best practices and avoid audit findings... Use PasswordInput widget for ldap_bind_password.

Use PasswordInput widget for ldap_bind_password.

---

crits/config/forms.py

To adhere to best practices and avoid audit findings... Use PasswordInput widget for ldap_bind_password.

Use PasswordInput widget for ldap_bind_password in stable_4

---

crits/settings.py

Backport from master to avoid of some django issues.
The story is as follows:
After playing recently with stable_4, I ran into issues with how sessions are handled between different versions of the Django (mainly 1.7-1.8-1.9 IIRC). As a part of the fix that I made to get the Django 1.8 to work had to do with overloading the one of the functions with a functional equivalent from the earlier version of Django. That was done due to errors that were popping up when the Django would be updated or downgraded and there would be still some session data in the database causing the exceptions to be thrown. To avoid this altogether, I've switched master to use signed_cookies, this patch does the same for  stable_4.

Switch SESSION_ENGINE to signed_cookies on stable_4

---

crits/core/management/commands/runscript.py

This script used to work as expected, but we were recently unable to run the following successfully:
$ python manage.py runscript crits_scripts daily_indicators
We noticed this Pull Request and made the change above in our local instance to fix the issue.
https://github.com/crits/crits/pull/1026/

Updated runscript.py

---

crits/core/handlers.py

When downloading a TLO, If the user selects options that result in nothing to download, and the selected Result Format is "zip", an exception occurs. This fix checks for an empty list of json_docs and produces an appropriate error message instead.

Avoid exception at download if there are no docs to return

---

crits/core/management/commands/bucket_counts.py

The bucket_counts management command was looping through every TLO to count the buckets.  This was taking minutes to complete with a medium-sized data set.  Using MongoDB's aggregate function, it now takes seconds.  Completes over 30x faster with our data set.

Improve performance of bucket_counts management command

---

crits/indicators/handlers.py

IPv6 address indicators, in particular, are normalized before being added to CRITs.  While the "value" attribute is correctly updated, the indicator's "lower" attribute is not, which can lead to indicators that are effectively duplicate.  This change fixes that issue and also preserves the original given indicator value for the "Seen on X as X" note in the indicator's description.

Set Indicator lower value after normalization

---

crits/certificates/handlers.py
crits/core/handlers.py
crits/core/management/commands/create_default_collections.py
crits/notifications/handlers.py
crits/objects/handlers.py
crits/raw_data/handlers.py
crits/samples/handlers.py
crits/signatures/handlers.py

Replacing some len() with .count(). It makes DB do work rather than Python. This also should reduce lag in those places, as Python will not pull down the results of the query, and will not have to iterate through them to count them.
Also added a note about SetOnInsert being supported by Mongoengine 8.0.0,
so that the query can be changed to run under mongoengine rather than PyMongo

Replacing len() on Querysets with .count() to make the DB do the heavy lifting 

---

crits/core/views.py

An attacker can make requests directly to the administrator control panel without going through the user interface. In doing so there is no validation that the person using the control panel is authenticated. As a result, an attacker can create a request to create a new user (or modify an existing user) with the highest level of permissions while unauthenticated. 
Adding the user_can_view test resolves this issue.

Fix bug where unauthorized users could interact with source_access
