crits/crits

crits/core/errors.py
crits/core/static/css/core.css
crits/core/templates/400.html
crits/core/templates/403.html
crits/core/templates/500.html
crits/dashboards/views.py
crits/urls.py
extras/www/static/css/core.css

Adds support for custom 400, 403, 404 functions along with the previous
500 error page.
Also cleaned up some stuff from the previous error page commit.

More custom error pages.

---

crits/standards/handlers.py

Add logging of exceptions that occur when parsing STIX documents.

---

crits/services/views.py

fix for #389

---

script/bootstrap

The bootstrap scripts works mostly fine, it's just missing a couple sudos and 2 dependencies for Ubuntu 14.04.
I've added them in this PR.
Cheers.

missing Ubuntu deps: libssl-dev swig + sudo

---

crits/core/form_consts.py
crits/domains/forms.py
crits/domains/handlers.py

Domain and IP Add

---

crits/raw_data/handlers.py

This PR is aiming to make an adjustment in RawData' docstrings function handle_raw_data_file() to bring it to parity with the code of the function.
There are no code changes just the comments pertaining to the returned keys are updated to reflect the current code.

RawData update docstrings

---

crits/core/templates/tickets_row_widget.html

Usability enhancement for tickets, clicking on a ticket number now takes you to a search for related artifacts for the referenced ticket.

Usability enhancement for tickets

---

README.md

One could also say: 'the analyst' instead of 'analyst' here, but I'm not sure of the original intention.

Correct a sentence where 'analyst' might want to be 'analysts'

---

requirements.txt

Removing pydot from requirements.txt

pydot is no longer needed

---

crits/core/static/js/core.js
crits/core/static/js/dialogs.js
crits/core/templates/base.html
extras/www/css/jquery-themes/Christina/style.css
extras/www/css/jquery-themes/Fil/style.css
extras/www/css/jquery-themes/Midnight/style.css
extras/www/css/jquery-themes/default/style.css
extras/www/static/js/core.js
extras/www/static/js/dialogs.js

When you select text a small floating menu will pop up allowing you to create a new Indicator, Domain, or IP from the value you selected. All it does is open up the form and insert the selected value into it.
Could be expanded in the future to do more stuff I guess, but at least the framework for it is there. I can think of some pretty neat stuff to do with selected text but this seemed like the most obvious.

New TLO from selected text

---

crits/core/handlers.py

This commit fixes backdoor and exploit searching and also adds the tabs
for them to the search results.

Add backdoor and exploit searching.

---

crits/campaigns/handlers.py
crits/core/handlers.py

Added encodeURIComponent() for data.record.name in generate_sector_jtable() and generate_bucket_jtable()

Fixes for sector and bucket jtables

---

crits/backdoors/templates/backdoor_detail.html
crits/core/handlers.py
crits/core/sector.py
crits/exploits/templates/exploit_detail.html

Add backdoor and templates to sector jtable.
Add backdoor and exploit counts to sector objects (default to 0).
Add sector to backdoor and exploit templates.

Sector backdoor and exploit

---

crits/services/templates/services_edit_config.html

the old link was taking you to a badly rendered page, the fix takes you back to Service listing page

Fix the "back link"

---

crits/screenshots/screenshot.py

Added a check for name attribute to allow BytesIO to be passed to add_screenshot().
Changed StringIO.StringIO to more portable io.BytesIO.

Screenshots update

---

crits/samples/handlers.py

Unrar and Unzip were still broken. This will fix it.

More Vocab fixes

---

crits/services/templates/services_analysis_widget.html

https://github.com/crits/crits/issues/563

Added id attribute to help handle with any jquery manipulations

---

.gitmodules

There was some cruft left over that I forgot to remove in #569 .

Remove leftover salt remnants.

---

contrib/mongo/mongod_start.sh
script/bootstrap

I took some niceties from #510 and #511, and added some other fixes. Tested on a fresh install of CentOS 6.

Bootstrap fixes for CentOS/RHEL

---

crits/raw_data/handlers.py

Please see https://github.com/crits/crits/issues/596 for details.

fix for issue #596

---

crits/objects/static/js/objects.js
extras/www/static/js/objects.js

Implementing suggested changes from #617 and Closes #617

Fixing advanced search panel on the right side.

---

requirements.txt
script/bootstrap

- Added exit for some common error cases, so that the script doesn't continue to execute on some errors
- Added a menu for common development tasks
- Added an error message suggesting workarounds for m2crypto :
e.g. apt-get install python-m2crypto or
"pip install git+https://github.com/martinpaljak/M2Crypto.git"

Bootstrap updates

---

crits/raw_data/handlers.py

This has to do with the second error reported in #633.
I think that rel.rel_object_id should be rel.object_id... 
Change seems to be working :)

Fix a typo in handle_raw_data_file()

---

crits/core/api.py
crits/core/handlers.py
crits/core/views.py
crits/indicators/handlers.py
crits/indicators/views.py

This might be longer than necessary so I apologize in advance.
This PR is in reference to a google groups discussion located [here]( https://groups.google.com/forum/#!topic/crits-users/P4CZQCGTTLA) .
The purpose of these changes is to expand the API, using "PATCH" requests which were enabled in https://github.com/crits/crits/pull/449
The following core functions are exposed with these changes:
Core:
status_update
ticket_add
ticket_update
ticket_remove
source_add_update
source_remove
action_add
action_update
action_remove
description_update
Indicator:
set_indicator_attack_type
set_indicator_threat_type
activity_add
activity_update
activity_remove
ci_update (Update confidence or impact)
I followed the following guidelines:
1.  Only "views.py" and "handlers.py" files are modified.  No "core" …

API Enhancement

---

crits/emails/handlers.py

This relates to discussion in issue #678

Use StringIO to decode email headers in unicode

---

script/bootstrap

Also update the error message to be more helpful

bootstrap fix to make M2Crypto build on OSX

---

script/bootstrap

create folders before installing mongo
and check for /data/db

small bootstrap fixes

---

UPDATING

Forgot to mention the updates needed to run on 1.7.

Updated UPDATING

---

crits/indicators/handlers.py
crits/samples/handlers.py

This makes a few changes that are used by the updated TAXII service, but really they should probably be in there anyway. :)

Allow setting of description field for Indicators & Samples

---

crits/settings.py

fix SESSION_KEY for REMOTE_USER

---

script/bootstrap

and pip was missing '-U' for everything else other than OSX

Make the bootstrap more proxy friendly

---

crits/core/static/js/dialogs.js
crits/events/forms.py
crits/samples/handlers.py
crits/samples/views.py
extras/www/static/js/dialogs.js

core.js was missing in a collectstatic run so it was caught here. Some
of the dialogs which had a function mapped when opening lost it because
it was consumed by the related newPersona. This adds them back.
Also fixed an issue with uploading Samples using 7zip where the
appropriate relationship fields were being passed in but the arguments
weren't there so it was failing.

Fixes some issues with dialogs.

---

crits/core/core_migrate.py
crits/core/crits_mongoengine.py
crits/core/management/commands/upgrade.py
crits/samples/migrate.py

This smooths out the upgrade progress with better error handling and more information to help solve migration issues.

Improvements to upgrade script and migrations

---

crits/samples/handlers.py

Fix a missing coma

---

crits/samples/handlers.py

Fix an issue where data would be overwritten by a triage.
This change just moves the relationships and saving of those relationships to BEFORE the triage occurs.

Sample Relationships To TLO Overwritten By Triage Object

---

extras/www/css/jquery-themes/Fil/style.css

One of the image files for the "Fil" query-theme is missing: ui-bg_highlight-soft_75_d7d5c0_1x100.png
Changing the "background" property to just use the color.

Remove reference to missing theme image file

---

crits/notifications/handlers.py

When a user attempts to add a Comment to a TLO that doesn't have a Source field, they are given no indication that the comment was added successfully. No response message is displayed and the page is not updated. However, if the page is reloaded, the user can see that the comment was indeed added.
This is because adding the comment triggers the creation of a notification. The code attempts to grab the source from the TLO, but since the TLO has no Source, an error occurs. The code now only pulls source data if the object has source data.

Handle Source-less TLOs for Comment notifications

---

crits/indicators/handlers.py

Indicator vocabulary replaced "URI - URL" with just "URI".  URIs don't require the "://" that was required for URLs. Also, a URI won't necessarily contain a domain or IP like a URL would.  This removes those restrictions.

Modify verification for URL to URI vocab change

---

crits/ips/api.py
crits/samples/api.py
documentation/help_main.html
documentation/help_main.txt

May also wanna update the Wiki with the fix. I just implemented it how the rest of stuff is.

Include description option in API for CRITS

---

documentation/help_main.html
documentation/help_main.txt

Extra documentation explaining the PATCH API. Also explains issue #788

Modifed help to include examples of using PATCH API

---

script/bootstrap

tr was not filtering properly, allowing things not in the specified set to go through

Fix secret generation

---

crits/core/templates/base.html
crits/dashboards/templates/dashboard.html

1. Fix the template issue on Django 1.10
2. Always display the current year on the footer

two small fixes

---

crits/services/handlers.py

If a service produces bad data in its analysis results such that the data can't be written to the DB, the resulting error is not handled.  This leads to an endless spinning circle in the `Analysis` tab of a TLO as if the task never completes.
This fix assumes that the bad data is most likely in the `results` component and attempts to clear that data only while adding a log entry with the error.  If the DB update still fails (bad data in log entry?), another update is attempted with only the new error log entry.
This more gracefully handles errors like the one I was seeing in crits/crits_services#276

Handle exception caused by bad data in AnalysisResult

---

LICENSE
crits/core/templates/about.html
documentation/src/conf.py
script/bootstrap
script/server

Make things 2016.

---

requirements.txt
script/bootstrap

- Add support for Fedora
- Update the mongodb to 2.6.12
- try to update pip/setuptools to the latest

Updates to bootstrap.

---

crits/services/core.py

- commented out useless logfile polluters ("Found service subclass", "Registering Service")
- Added service name, and elapsed runtime to the "Finished analysis" messages.

Make the service logging a bit more useful

---

.mention-bot

Feel free to mention me directly if you'd like my input on anything 😀 
https://github.com/facebook/mention-bot#configuration

Configure mention-bot with users to never notify

---

UPDATING
crits/settings.py
crits/urls.py
requirements.txt

- Wrapped template loaders in cached.Loader  (https://docs.djangoproject.com/en/dev/ref/templates/api/#django.template.loaders.cached.Loader)
- Added some nice debug toolbars

Wrapped template loaders in cached.Loader and added some nice debug toolbars

---

crits/core/handlers.py
crits/core/templates/base.html

I thought that it would be useful to add a few common things to the dropdown such as SHA256, impfuzzy, ticket.

Expand advanced search options

---

crits/core/totp.py

Also fix a typo.  Fixes issue #862

Use gen_random parameter instead of magic number

---

crits/core/crits_mongoengine.py
crits/core/fields.py
crits/settings.py

Mongoengine 0.8.8 - 0.11.0 should work with this pull.

Better support for various versions of MongoEngine

---

crits/screenshots/handlers.py

Borrowed some code from the PCAP handler to make sure you could add sources as lists as well. This should fix the preview service.

Allow for adding from sources or source lists.

---

crits/screenshots/handlers.py

source param now takes EmbeddedSource and a list of embedded sources as well as string.

Update comments for add_screenshot()

---

extras/nginx.conf
extras/nginx_uwsgi.ini

Nginx and uwsgi example configs to demonstrate how to run CRITs on Nginx.

Nginx and uwsgi example configs

---

crits/config/views.py
crits/core/handlers.py
crits/core/user_tools.py
crits/core/views.py

There were some functions (I'm sure there's more) that were ignoring the
fact that we had the user object already and was still querying the
database for them.

If we have the user already, don't query again.

---

script/bootstrap

Ensure that we have autoconf automake and libtool to be able to build packages (such as yara) from source.

Update packages for CentOS, RHEL, Fedora in bootstrap

---

DEPENDENCIES

This will make it match requirements.txt

Update Django version in DEPENDENCIES

---

crits/actors/api.py
crits/backdoors/api.py
crits/campaigns/api.py
crits/certificates/api.py
crits/comments/api.py
crits/domains/api.py
crits/emails/api.py
crits/events/api.py
crits/exploits/api.py
crits/indicators/api.py
crits/ips/api.py
crits/pcaps/api.py
crits/raw_data/api.py
crits/samples/api.py
crits/screenshots/api.py
crits/signatures/api.py
crits/targets/api.py

This enables ordering of the API query results.

Added ordering for the tastypie API

---

crits/core/crits_mongoengine.py

With some versions of mongoengine we're getting the following error:
File "/data/crits/crits/core/crits_mongoengine.py" in _custom_save
363.                                          _refs=_refs)
File "/data/crits/venv2/local/lib/python2.7/site-packages/mongoengine/document.py" in save
241.                     object_id = collection.save(doc, **write_concern)
File "/data/crits/venv2/local/lib/python2.7/site-packages/pymongo/collection.py" in save
416.             return self.insert(to_save, manipulate, safe, check_keys, **kwargs)
Exception Type: TypeError at /source_add/
Exception Value: _insert() takes at most 4 arguments (6 given)
This backport is going to fix it as it does on master branch.

Backporting some mongoengine compatibility fixes from master

---

crits/core/views.py

Render forms when requested as opposed to rendering every form at page load via the page context processor. This update should drastically increase performance of the crits GUI.

Form rendering improvement

---

crits/core/views.py

This should lighten the load a little by moving it out of the base_context.

move loaded_mods out of base_context
